---
title: "Credit Card Fraud Detection"
author: "Indu Sen"
date: "2024-02-05"
output: html_document
---

```{r setup, include=true}
knitr::opts_chunk$set(echo = TRUE)
```

# Credit Card Fraud Detection 

## Load libaries

```{r, include=false}
library(ranger)
library(caret)
library(data.table)
```

## Read dataset into a dataframe

```{r}
data <- read.csv("/Users/indusen/Downloads/creditcard.csv")
```

## Exploratory analysis

```{r}
data.table(data)
```

```{r}
summary(data)
table(data$Class)
names(data)
```
### Summary of Amount

```{r}
summary(data$Amount)

sd(data$Amount)

IQR(data$Amount)

var(data$Amount)
```
## Data Manipulation

```{r}
data$Amount <- scale(data$Amount) # normalization
```

```{r}
data2 <- data[,-c(1)] # removing time from data
head(data2)
```
```{r}
set.seed(12)
library(caTools)
```

```{r}
sample_data <- sample.split(data2$Class, SplitRatio = 0.80)
```

```{r}
train_data <- subset(data2,sample_data==TRUE)
```

```{r}
test_data <- subset(data2,sample_data == FALSE)
```

```{r}
dim(train_data)
dim(test_data)
```

## Logistic Regression

```{r}
Logistic_Model <- glm(Class~., test_data, family = binomial())
summary(Logistic_Model)

plot(Logistic_Model)

```

```{r}
Logistic_Model1 <-glm(Class~., train_data, family = binomial())
summary(Logistic_Model1)

plot(Logistic_Model1)

```

## ROC Curve

```{r}
library(pROC)
lr.predict <- predict(Logistic_Model1,test_data,probability = TRUE)
auc.gb <- roc(test_data$Class, lr.predict, plot = TRUE, col = "green")
```

## Decision Tree

```{r}
library(rpart)
library(rpart.plot)
```

```{r}
decision_model <- rpart (Class ~ . , data, method = "class")
predicted_val <- predict(decision_model, data, type = "class")
probability <- predict(decision_model, data, type = "prob")
rpart.plot(decision_model)
```

## Using Neural Networks

```{r}
library(neuralnet)
NN_model <- neuralnet::neuralnet(Class~.,train_data,linear.output = FALSE)
plot(NN_model)
```

```{r}
predNN <- compute(NN_model, test_data)
resultNN <- predNN$net.result
resultNN = ifelse(resultNN>0.6,1,0)
```
