---
title: "U.S. Colleges"
author: "Indu Sen"
date: "2024-01-30"
output:
  html_document: default
  pdf_document: default
---

# Load Libaries 

```{r}

library(tidyverse)

library('ISLR')
```

### Questions

Do colleges with larger full-time enrollments have lower graduation rates?

 Is this different for public/private institutions? If it different for more selective schools?

```{r}
?College
glimpse(College)
```

# Exploratory graphics

```{r}

ggplot(College, aes(x = Grad.Rate)) +
    geom_histogram() # There is an outlier 

suspicious_outlier <- filter(College, Grad.Rate >=100)
view(suspicious_outlier)

ggplot(College, aes(x=log10(F.Undergrad), y = Grad.Rate)) + 
    geom_point()

```
```{r}

college_sm <- College %>%
    mutate(log_full = log10(F.Undergrad)) %>%
    select(Grad.Rate,
           log_full,
           Private,
           Top25perc)

view(college_sm)

```

# Modeling
```{r}

ggplot(College, aes(x=log10(F.Undergrad), y = Grad.Rate)) + 
    geom_point() +
    geom_smooth(method = "lm")

model_undergrad <- lm(Grad.Rate ~ log_full,
                      data = college_sm)

summary(model_undergrad)

plot(model_undergrad)

```
```{r}

#What about Private?


ggplot(College, aes(x=log10(F.Undergrad), y = Grad.Rate, color = Private)) + 
    geom_point() +
    geom_smooth(method = "lm",
                se = FALSE) +
    scale_color_brewer(palette = "Dark2")

model_private <-lm(Grad.Rate ~ Private + log_full,
                   data = college_sm)

summary(model_private)
```
```{r}
# Interaction: private and F.Undergrad

model_private_int <- lm(Grad.Rate ~ Private * log_full, data = college_sm)

summary(model_private_int)
```
```{r}

# What about Top 25 percent?

model_top <- lm(Grad.Rate ~ Private + log_full + Top25perc, data = college_sm)

summary(model_top)

plot(model_top)

```

